- id: '1663043688965'
  alias: Late Night Garage Closer
  description: Tries to close the garage door every 15 minutes from 10 pm to 5 am
  trigger:
  - platform: device
    device_id: 1866389b89ebb7c25f7e5a3da59e7643
    domain: cover
    entity_id: cover.garage_door
    type: opened
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: time
    before: 07:00:00
    after: '22:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.garage_door
  mode: single
- id: '1663045196223'
  alias: Disable Late Night Garage
  description: Disables the Late Night Garage Door Automation temporarily
  trigger:
  - platform: event
    event_type: ''
  condition: []
  action:
  - service: automation.turn_off
    data:
      stop_actions: false
    target:
      entity_id: automation.late_night_garage_closer
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.late_night_garage_closer
  mode: single
- id: '1663345317722'
  alias: Screen Light Dimmer
  description: Dims the screen of a terminal based on the Lumins input
  trigger:
  - platform: device
    type: turned_on
    device_id: 8ffdbe9a54be7e65369c955ff0d796b9
    entity_id: switch.fire_screen
    domain: switch
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fire_tablet_1_light_sensor
        above: 15
        below: 25
      sequence:
      - device_id: 8ffdbe9a54be7e65369c955ff0d796b9
        domain: number
        entity_id: number.fire_screen_brightness
        type: set_value
        value: 255
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fire_tablet_1_light_sensor
        above: 10
        below: 15
      sequence:
      - device_id: 8ffdbe9a54be7e65369c955ff0d796b9
        domain: number
        entity_id: number.fire_screen_brightness
        type: set_value
        value: 191
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fire_tablet_1_light_sensor
        above: 7
        below: 10
      sequence:
      - device_id: 8ffdbe9a54be7e65369c955ff0d796b9
        domain: number
        entity_id: number.fire_screen_brightness
        type: set_value
        value: 127
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fire_tablet_1_light_sensor
        above: 4
        below: 7
      sequence:
      - device_id: 8ffdbe9a54be7e65369c955ff0d796b9
        domain: number
        entity_id: number.fire_screen_brightness
        type: set_value
        value: 63
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fire_tablet_1_light_sensor
        above: 0
        below: 4
      sequence:
      - device_id: 8ffdbe9a54be7e65369c955ff0d796b9
        domain: number
        entity_id: number.fire_screen_brightness
        type: set_value
        value: 0
  mode: single
- id: '1663642159401'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      exclude:
        entity_id:
        - sensor.pixel_5a_battery_level
        - sensor.leeza_battery_level
      threshold: 15
      actions:
      - service: notify.mobile_app_pixel_5a
        data:
          message: '{{sensors}} is low on battery'
- id: set_climate_controller_hvac_mode
  alias: Set climate_controller HVAC Mode
  description: Whenever the target_temperature changes on climate_controller, set
    hvac to auto
  trigger:
  - platform: state
    entity_id: climate.climate_controller
    attribute: temperature
  condition:
    not:
    - condition: state
      entity_id:
      - climate.climate_controller
      state: auto
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: auto
    target:
      entity_id: climate.climate_controller
- id: set_climate_entities_temp
  alias: Set Climate Entities Temp
  description: Every 15 minutes or whenever climate controller changes states -> decide
    which hvac mode and temperature all climate entities should be set to
  trigger:
  - platform: time_pattern
    minutes: /15
  - platform: state
    entity_id: climate.climate_controller
    to:
  - platform: state
    entity_id: climate.climate_controller
    attribute: temperature
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id:
        - climate.climate_controller
        state: 'off'
      sequence:
        service: script.deactivate_all_climate_entities
        data:
          heat_pumps:
          - climate.2354_dining_room_heat_pump
          - climate.2354_kitchen_heat_pump
          boiler_thermostat: climate.2354_ecobee_thermostat
    - conditions:
      - condition: state
        entity_id:
        - binary_sensor.use_heat_pump
        state: 'on'
      sequence:
      - service: script.set_heat_pump_hvac_mode
      - service: climate.set_temperature
        data:
          temperature: '{{ state_attr(''climate.climate_controller'', ''temperature'')
            | float }}'
        target:
          entity_id:
          - climate.2354_dining_room_heat_pump
          - climate.2354_kitchen_heat_pump
      - service: climate.set_temperature
        data:
          temperature: 65
        target:
          entity_id:
          - climate.2354_ecobee_thermostat
    - conditions:
      - condition: state
        entity_id:
        - binary_sensor.use_heat_pump
        state: 'off'
      sequence:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: 'off'
        target:
          entity_id:
          - climate.2354_dining_room_heat_pump
          - climate.2354_kitchen_heat_pump
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: '{{ state_attr(''climate.climate_controller'', ''temperature'')
            }}'
        target:
          entity_id:
          - climate.2354_ecobee_thermostat
    default:
    - service: climate.set_preset_mode
      data:
        preset_mode: BACKUP HEAT
      target:
        entity_id: climate.2354_ecobee_thermostat
- id: '1664911918906'
  alias: Set 2354 Climate Entities
  description: This automation will set all the thermostat entities in 2354
  use_blueprint:
    path: climate/set_climate_entities.yaml
    input:
      climate_controller: climate.climate_controller
      e_heat_pump: climate.2354_kitchen_heat_pump
      w_heat_pump: climate.2354_dining_room_heat_pump
      boiler_therm: climate.2354_ecobee_thermostat
      boiler_set_temp_script: script.set_2354_boiler_temp
      e_hp_set_temp_script: script.set_2354_e_hp_temp
      w_hp_set_temp_script: script.set_2354_w_hp_temp
