- id: '1663043688965'
  alias: Late Night Garage Closer
  description: Tries to close the garage door every 15 minutes from 10 pm to 5 am
  trigger:
  - platform: device
    device_id: 1866389b89ebb7c25f7e5a3da59e7643
    domain: cover
    entity_id: cover.garage_door
    type: opened
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: time
    before: 07:00:00
    after: '22:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.garage_door
  mode: single
- id: '1663045196223'
  alias: Disable Late Night Garage
  description: Disables the Late Night Garage Door Automation temporarily
  trigger:
  - platform: event
    event_type: ''
  condition: []
  action:
  - service: automation.turn_off
    data:
      stop_actions: false
    target:
      entity_id: automation.late_night_garage_closer
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.late_night_garage_closer
  mode: single
- id: '1663345317722'
  alias: Screen Light Dimmer
  description: Dims the screen of a terminal based on the Lumins input
  trigger:
  - platform: device
    type: turned_on
    device_id: 8ffdbe9a54be7e65369c955ff0d796b9
    entity_id: switch.fire_screen
    domain: switch
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fire_tablet_1_light_sensor
        above: 15
        below: 25
      sequence:
      - device_id: 8ffdbe9a54be7e65369c955ff0d796b9
        domain: number
        entity_id: number.fire_screen_brightness
        type: set_value
        value: 255
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fire_tablet_1_light_sensor
        above: 10
        below: 15
      sequence:
      - device_id: 8ffdbe9a54be7e65369c955ff0d796b9
        domain: number
        entity_id: number.fire_screen_brightness
        type: set_value
        value: 191
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fire_tablet_1_light_sensor
        above: 7
        below: 10
      sequence:
      - device_id: 8ffdbe9a54be7e65369c955ff0d796b9
        domain: number
        entity_id: number.fire_screen_brightness
        type: set_value
        value: 127
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fire_tablet_1_light_sensor
        above: 4
        below: 7
      sequence:
      - device_id: 8ffdbe9a54be7e65369c955ff0d796b9
        domain: number
        entity_id: number.fire_screen_brightness
        type: set_value
        value: 63
    - conditions:
      - condition: numeric_state
        entity_id: sensor.fire_tablet_1_light_sensor
        above: 0
        below: 4
      sequence:
      - device_id: 8ffdbe9a54be7e65369c955ff0d796b9
        domain: number
        entity_id: number.fire_screen_brightness
        type: set_value
        value: 0
  mode: single
- id: '1663642159401'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      exclude:
        entity_id:
        - sensor.pixel_5a_battery_level
        - sensor.leeza_battery_level
      threshold: 15
      actions:
      - service: notify.mobile_app_pixel_5a
        data:
          message: '{{sensors}} is low on battery'
# - id: '1664911918906'
#   alias: Set 2354 Climate Entities
#   description: This automation will set all the thermostat entities in 2354
#   use_blueprint:
#     path: climate/set_climate_entities.yaml
#     input:
#       climate_controller: climate.climate_controller
#       e_heat_pump: climate.2354_kitchen_heat_pump
#       w_heat_pump: climate.2354_dining_room_heat_pump
#       boiler_therm: climate.2354_ecobee_thermostat
#       boiler_set_temp_script: script.set_2354_boiler_temp
#       e_hp_set_temp_script: script.set_2354_e_hp_temp
#       w_hp_set_temp_script: script.set_2354_w_hp_temp
# - id: '1667746744999'
#   alias: 2354 Climate Manual Mode
#   description: This automation enables or disables the climate automations for 2354
#     depending on the state of a "manual mode" boolean helper
#   trigger:
#   - platform: state
#     entity_id:
#     - input_boolean.2354_manual_climate
#   condition: []
#   action:
#   - if:
#     - condition: state
#       entity_id: input_boolean.2354_manual_climate
#       state: 'off'
#     then:
#     - service: automation.turn_on
#       data: {}
#       target:
#         entity_id:
#         - automation.set_2354_climate_entities
#         - automation.set_climate_entities_temp
#         - automation.set_climate_controller_hvac_mode
#     - service: climate.set_hvac_mode
#       data:
#         hvac_mode: auto
#       target:
#         entity_id: climate.climate_controller
#     else:
#     - service: automation.turn_off
#       data:
#         stop_actions: false
#       target:
#         entity_id:
#         - automation.set_2354_climate_entities
#         - automation.set_climate_controller_hvac_mode
#         - automation.set_climate_entities_temp
#     - service: climate.set_hvac_mode
#       data:
#         hvac_mode: 'off'
#       target:
#         entity_id: climate.climate_controller
#   mode: single
- id: '1667797747180'
  alias: 'Reload Fully Browser'
  description: For when guests get snoopy
  trigger:
  - platform: state
    entity_id:
    - sensor.2356_dining_fully_browser_current_page
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: button.press
    data: {}
    target:
      entity_id: button.2356_dining_fully_browser_load_start_url
  mode: single
