# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: Booth St. House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 692
  unit_system: imperial
  time_zone: "America/Chicago"
  country: "US"
  currency: USD
  internal_url: "http://homeassistant.local:8123"

# Text to speech
tts:
  - platform: google_translate

lovelace:
  resources:
    - url: /local/config-template-card.js
      type: module
    - url: /local/state-switch.js
      type: module
    - url: /local/custom-lovelace/swipe-card/swipe-card.js
      type: module
    - url: /local/clock-weather-card.js
      type: module

template:
  - sensor: !include sensors.yaml
  - binary_sensor:
      # Get preferred HVAC service
      - name: use_heat_pump
        state: >
          {% set outdoorTemp = states('sensor.outside_temp') | int %}
          {% set hvacTransTemp = states('input_number.use_hp_temp') | int %}
          {% if (outdoorTemp >= hvacTransTemp) %}
            True
          {% elif (outdoorTemp < hvacTransTemp) %}
            False
          {% else %}
            False
          {% endif %}

group:
  heatpumps:
    name: 2354_heat_pump_group
    entities:
      - climate.2354_dining_room_heat_pump
      - climate.2354_kitchen_heat_pump

climate:
  - platform: climate_template
    name: 2354_climate_controller
    modes:
      - heat
      - cool
      - "off"
    min_temp: 65
    max_temp: 85
    current_temperature_template: "{{ states('sensor.2354_average_indoor_temperature') | int }}"
    target_temperature_template: "{{ state_attr('climate.2354_climate_controller', 'temperature') | int }}"
    set_temperature:
      - choose:
        - conditions: >
            "{{  states('climate.2354_climate_controller') == 'heat' }}"
          sequence:
            - service: climate.set_temperature
              data:
                entity_id: climate.2354_ecobee_thermostat
                temperature: "{{ state_attr('climate.2354_climate_controller', 'temperature') | int }}"
        - conditions: >
            "{{  states('climate.2354_climate_controller') == 'cool' }}"
          sequence:
            - service: climate.set_temperature
              data:
                entity_id: climate.2354_dining_room_heat_pump
                temperature: "{{ state_attr('climate.2354_climate_controller', 'temperature') | int }}"
            - service: climate.set_temperature
              data:
                entity_id: climate.2354_kitchen_heat_pump
                temperature: "{{ state_attr('climate.2354_climate_controller', 'temperature') | int }}"
            - service: climate.set_temperature
              data:
                entity_id: climate.2354_ecobee_thermostat
                temperature: 65
        - conditions: >
            "{{  states('climate.2354_climate_controller') == 'off' }}"
          sequence:
            - service: climate.set_temperature
              data:
                entity_id: climate.2354_ecobee_thermostat
                temperature: 65
    set_hvac_mode:
      - choose:
        - conditions: >
            "{{  states('climate.2354_climate_controller') == 'heat' }}"
          sequence:
            - service: climate.set_hvac_mode
              data:
                entity_id: climate.2354_ecobee_thermostat
                hvac_mode: "{{ states('climate.2354_climate_controller') }}"
            - service: climate.set_hvac_mode
              data:
                entity_id: climate.2354_dining_room_heat_pump
                hvac_mode: "off"
            - service: climate.set_hvac_mode
              data:
                entity_id: climate.2354_kitchen_heat_pump
                hvac_mode: "off"
        - conditions: >
            "{{  states('climate.2354_climate_controller') == 'cool' }}"
          sequence:
            - service: climate.set_hvac_mode
              data:
                entity_id: climate.2354_dining_room_heat_pump
                hvac_mode: "{{ states('climate.2354_climate_controller') }}"
            - service: climate.set_hvac_mode
              data:
                entity_id: climate.2354_kitchen_heat_pump
                hvac_mode: "{{ states('climate.2354_climate_controller') }}"
        - conditions: >
            "{{  states('climate.2354_climate_controller') == 'off' }}"
          sequence:
            - service: climate.set_hvac_mode
              data:
                entity_id: climate.2354_dining_room_heat_pump
                hvac_mode: "off"
            - service: climate.set_hvac_mode
              data:
                entity_id: climate.2354_kitchen_heat_pump
                hvac_mode: "off"

automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml
