# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: Booth St. House
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 692
  unit_system: imperial
  time_zone: "America/Chicago"
  country: "US"
  currency: USD
  internal_url: "http://homeassistant.local:8123"

# Text to speech
tts:
  - platform: google_translate

lovelace:
  resources:
    - url: /local/config-template-card.js
      type: module
    - url: /local/state-switch.js
      type: module
    - url: /local/custom-lovelace/swipe-card/swipe-card.js
      type: module
    - url: /local/clock-weather-card.js
      type: module

template:
  - sensor: !include sensors.yaml
  - binary_sensor:
      # Get preferred HVAC service
      - name: use_heat_pump
        state: >
          {% set outdoorTemp = states('sensor.outside_temp') | int %}
          {% set hvacTransTemp = states('input_number.use_hp_temp') | int %}
          {% if (outdoorTemp >= hvacTransTemp) %}
            True
          {% elif (outdoorTemp < hvacTransTemp) %}
            False
          {% else %}
            False
          {% endif %}

group:
  heatpumps:
    name: 2354_heat_pump_group
    entities:
      - climate.2354_dining_room_heat_pump
      - climate.2354_kitchen_heat_pump

climate:
  - platform: climate_template
    name: 2354_climate_controller
    modes:
      - auto
      - heat
      - cool
      - "off"
    min_temp: 65
    max_temp: 85
    current_temperature_template: "{{ states('sensor.2354_average_indoor_temperature') | int}}"
    set_temperature:
      - service: climate.set_temperature
        data:
          entity_id: climate.climate_controller
          temperature: "{{ state_attr('climate.climate_controller', 'temperature')}}"
    set_hvac_mode:
      - condition: state
        entity_id:
          - climate.climate_controller
        state: "off"
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.climate_controller
          hvac_mode: "{{ states('climate.climate_controller')}}"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
