- id: set_climate_entities_temp
  alias: Set Climate Entities Temp
  description: Every 15 minutes or whenever climate controller changes states -> decide
    which hvac mode and temperature all climate entities should be set to
  trigger:
  - platform: time_pattern
    minutes: /15
  - platform: state
    entity_id: climate.climate_controller
    to:
  - platform: state
    entity_id: climate.climate_controller
    attribute: temperature
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id:
        - climate.climate_controller
        state: 'off'
      sequence:
        service: script.deactivate_all_climate_entities
        data:
          heat_pumps:
          - climate.2354_dining_room_heat_pump
          - climate.2354_kitchen_heat_pump
          boiler_thermostat: climate.2354_ecobee_thermostat
    - conditions:
      - condition: state
        entity_id:
        - binary_sensor.use_heat_pump
        state: 'on'
      sequence:
      - service: script.set_heat_pump_hvac_mode
      - service: climate.set_temperature
        data:
          temperature: '{{ state_attr(''climate.climate_controller'', ''temperature'')
            | float }}'
        target:
          entity_id:
          - climate.2354_dining_room_heat_pump
          - climate.2354_kitchen_heat_pump
      - service: climate.set_temperature
        data:
          temperature: 65
        target:
          entity_id:
          - climate.2354_ecobee_thermostat
    - conditions:
      - condition: state
        entity_id:
        - binary_sensor.use_heat_pump
        state: 'off'
      sequence:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: 'off'
        target:
          entity_id:
          - climate.2354_dining_room_heat_pump
          - climate.2354_kitchen_heat_pump
      - service: climate.set_temperature
        data:
          hvac_mode: heat
          temperature: '{{ state_attr(''climate.climate_controller'', ''temperature'')
            }}'
        target:
          entity_id:
          - climate.2354_ecobee_thermostat
    default:
    - service: climate.set_preset_mode
      data:
        preset_mode: BACKUP HEAT
      target:
        entity_id: climate.2354_ecobee_thermostat