blueprint:
  name: Calculate Heat Pump Set Temperature
  domain: script
  description: >
    This script will calculate what the hp set temp shoudld be
    to achieve the climate controller set temp based on input
    temperature sensors
  input:
    heat_pump:
      name: Target Heat Pump
      description: the targeted heat pump to be calculated
      selector:
        entity:
          multiple: false
          domain: climate
    climate_controller:
      name: Climate Controller Thermostat
      description: The climate controller used to set the target temperature
      selector:
        entity:
          multiple: false
          domain: climate
    temp_sensor:
      name: Temperature Sensor
      description: The in house sensors 
      selector:
        entity:
          multiple: false
          domain: sensor
    current_hvac:
      name: Current HVAC Setting
      description: input_text representing the current hvac setting of the house (heat, cool, off)
      selector:
        entity:
          multiple: false
          domain: input_text
    hp_set_temp_helper:
      name: Heat Pump Set Temperature Helper
      description: this is the script output, it will save the calculated temp value to this
      selector:
        entity:
          multiple: false
          domain: input_number
sequence: 
  - alias: "set up variables"
    variables:
      heat_pump: !input heat_pump
      climate_controller: !input climate_controller
      temp_sensor: !input temp_sensor
      current_hvac: !input current_hvac
      hp_set_temp_helper: !input hp_set_temp_helper
      hp_local_temp: "{{ state_attr(heat_pump, 'current_temperature') | int }}"
      controller_set_temp: "{{ state_attr(climate_controller, 'temperature') | int }}"
      sensor_temp: "{{ states(temp_sensor) | int}}"
      set_temp_heat_modifier: "{{ states('input_number.set_temp_modifier_heat') }}"
  - alias: begin script
    choose:
    - alias: If the house hvac is set to heating...
      conditions: "{{ is_state(current_hvac, 'heat') }}"
      sequence:
        choose:
          - alias: >
              If the controller temp is warmer than the sensor temp
              and temp at the heat pump is warmer or the same as the controller temp 
              (ususally higher because its high up)
            conditions: 
            - "{{ (controller_set_temp > sensor_temp) }}"
            - "{{ (hp_local_temp >= controller_set_temp) }}"
            sequence:
              - alias: >
                  Add the controller set temp and the set temp modifier
                  and set the temp helper at that value
                service: input_number.set_value
                data:
                  value: "{{ controller_set_temp + set_temp_heat_modifier }}"
                target:  
                  entity_id: !input hp_set_temp_helper
          - alias: >
              Else if the controller set temp is colder or the same as the sensor temp
            conditions: "{{ controller_set_temp <= sensor_temp }}"
            sequence:
              - alias: >
                  Set the temp helper value to the controller set temp
                service: input_number.set_value
                data:
                  value: "{{ controller_set_temp }}"
                target:
                  entity_id: !input hp_set_temp_helper
        default:
          - alias: CATCH set the temp helper value to the controller set temp
            service: input_number.set_value
            data:
              value: "{{ controller_set_temp }}"
            target: 
              entity_id: !input hp_set_temp_helper
    - alias: If the house hvac is set to cooling...
      conditions: "{{ is_state(current_hvac, 'cool') }}"
      sequence:
        choose:
          - alias: IF the sensor temp is hotter than the controller set temp...
            conditions: "{{ controller_set_temp < sensor_temp }}"
            sequence:
              - alias: Set the temp helper value to the controller set temp
                service: input_number.set_value
                data:
                  value: "{{ controller_set_temp }}"
                target:  
                  entity_id: !input hp_set_temp_helper
          - alias: >
              ELSE IF the sensor temp is colder or the same as the controller set temp
              AND the heat pump sensor is warmer than the temp sensors
            conditions: 
            - "{{ controller_set_temp >= sensor_temp }}"
            - "{{ hp_local_temp > sensor_temp }}"
            sequence:
              - alias: >
                  subtract the temp modifier from the controller set temp
                  and set the temp helper to that value
                service: input_number.set_value
                data:
                  value: "{{ controller_set_temp - set_temp_heat_modifier}}"
                target:
                  entity_id: !input hp_set_temp_helper
        default:
          - alias: CATCH set the helper text to the controller set temp value
            service: input_number.set_value
            data:
              value: "{{ controller_set_temp }}"
            target:
              entity_id: !input hp_set_temp_helper

