blueprint:
  name: Set Temperature
  domain: script
  description: Set the temp for the active and inactive (optional) hvac devices
  input:
    target_thermostat:
      name: Target Thermostat
      description: This is the climate entity that will have it's temperature set
      selector:
        entity:
          multiple: false
          domain: climate
    temp_helper:
      name: Temperature Helper
      description: This holds a num value for the eastern heat pump
      selector:
        entity:
          multiple: false
          domain: input_number
    calculate_temp_script:
      name: Calculate Temperature Script
      description: This script calculates the set temp of the climate entity
      selector:
        entity:
          multiple: false
          domain: script
sequence:
  - alias: set up variables
    variables:
      temp_helper: !input temp_helper
  - alias: Calculate set temp
    service: !input calculate_temp_script
  - alias: Set target thermostat to new set temp
    service: climate.set_temperature
    data:
      temperature: "{{ states(temp_helper) }}"
    target:
      entity_id: !input target_thermostat
        
