blueprint:
  name: Calculate Heat Pump Set Temperature
  domain: script
  description: Calculates the set temperature for a heat pump based on inputs from sensors and a climate controller

  input:
    heat_pump:
      name: Target Heat Pump
      description: The targeted heat pump for calculation
      selector:
        target:
          entity:
            domain: climate
    climate_controller:
      name: Climate Controller Thermostat
      description: The climate controller used to set the target temperature
      selector:
        target:
          entity:
            domain: climate
    temp_sensor:
      name: Temperature Sensor
      description: The in-house sensors
      selector:
        target:
          entity:
            domain: sensor
    current_hvac:
      name: Current HVAC Setting
      description: Represents the current HVAC setting of the house (heat, cool, off)
      selector:
        target:
          entity:
            domain: input_text
    hp_set_temp_helper:
      name: Heat Pump Set Temperature Helper
      description: Stores the calculated set temperature value
      selector:
        target:
          entity:
            domain: input_number

sequence:
  - alias: Set up variables
    variables:
      heat_pump: "{{ state_attr(!input.heat_pump, 'current_temperature') | int }}"
      climate_controller: "{{ state_attr(!input.climate_controller, 'temperature') | int }}"
      sensor_temp: "{{ state(!input.temp_sensor) | int }}"
      current_hvac: "{{ state(!input.current_hvac) }}"
      set_temp_heat_modifier: "{{ state('input_number.set_temp_modifier_heat') }}"

  - alias: Calculate Heat Pump Set Temperature
    choose:
      - alias: If HVAC is set to 'heat' and climate controller > sensor temp and heat pump >= climate controller
        conditions: "{{ current_hvac == 'heat' and climate_controller > sensor_temp and heat_pump >= climate_controller }}"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: !input hp_set_temp_helper
            data:
              value: "{{ climate_controller + set_temp_heat_modifier }}"

      - alias: If HVAC is set to 'heat' and climate controller <= sensor temp
        conditions: "{{ current_hvac == 'heat' and climate_controller <= sensor_temp }}"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: !input hp_set_temp_helper
            data:
              value: "{{ climate_controller }}"

      - alias: If HVAC is set to 'cool' and climate controller < sensor temp
        conditions: "{{ current_hvac == 'cool' and climate_controller < sensor_temp }}"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: !input hp_set_temp_helper
            data:
              value: "{{ climate_controller }}"

      - alias: If HVAC is set to 'cool' and climate controller >= sensor temp and heat pump > sensor temp
        conditions: "{{ current_hvac == 'cool' and climate_controller >= sensor_temp and heat_pump > sensor_temp }}"
        sequence:
          - service: input_number.set_value
            target:
              entity_id: !input hp_set_temp_helper
            data:
              value: "{{ climate_controller - set_temp_heat_modifier }}"

    default:
      - service: input_number.set_value
        target:
          entity_id: !input hp_set_temp_helper
        data:
          value: "{{ climate_controller }}"